runtime: python38



env_variables:
  API_ID: "683428"
  API_HASH: "967b28d111f82b906b6f28da1ff04411"
  TOKEN: "1094295882:AAEF0PwOQKL88K6L5zslnpxKxWCGnfd0s3Q"
  SESSION: "1BJWap1wBu7H-ACv2TeYabz7Le_bC1MgTbnBWeZkfyDz8LO47KCTPSYnxHCkHqPE_RIF6bAvINpu7Tlvw0MwT-mtsnYrZD1k4WQ9bLZX9Ee2TTjEkBsb5g3PuwXr1ZG-SEXM_5BqC2TpuFepgX61YWPTg8TYDhFzFqBOO0MDo3NuLlJvT0yHxhQHeLoWZEszsoszZ4C9DGjj-lDhxmLbqiiGf6QH3zJE-Zn56d7U6nnWFPC6dKhESgBrwUZ8lC7rRlXcE2bqoR-NdgyvOMMa1lTXIXVnG6tq_a9dDeon0B9VP58MDdTmBDbw8Qiq-ROuXuE6M2MBfyy6b981VXC9TEz9T32QTruQ="
  DB_USER: "hunters_user"
  DB_PASS: "hunters"