runtime: python38



env_variables:
  API_ID: "683428"
  API_HASH: "967b28d111f82b906b6f28da1ff04411"
  TOKEN: "1094295882:AAEF0PwOQKL88K6L5zslnpxKxWCGnfd0s3Q"
  DB_USER: "hunters_user"
  DB_PASS: "hunters"
  WEBHOOK_URL: "https://new-project-265216.df.r.appspot.com/"